---
 - name: create default site configurations 
   template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf mode=0644
   notify: 
    - restart nginx service

 - name: Create site root directory
   file:
    path: "/opt/nginx/ansible"
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'

 - name: create home page for default site
   copy: src=index.html dest=/opt/nginx/ansible/index.html

       
 - name: create home page for ansible-sf site
   copy: src=index.php dest=/opt/nginx/ansible/index.php

 - name: create php virtual hosts
   template:
     src: php_vhost.j2
     dest: /etc/nginx/conf.d/{{ item.key }}.conf
   with_dict: "{{ nginx['phpsites'] }}"
   notify:
     - restart nginx service

