---
 - name: 'Install apt-transport-https'
   apt:
     name: 'apt-transport-https'

 - name: 'Add the nginx apt signing key'
   apt_key:
     url: 'http://nginx.org/keys/nginx_signing.key'
     state: 'present'
   notify:
     - restart nginx service

 - name: 'Add the official nginx repo'
   apt_repository:
     repo: 'deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release|lower }} nginx'
     state: 'present'
   notify:
     - restart nginx service

 - name: run the equivalent of "apt-get update" as a separate step
   apt: update_cache=yes

 - name: install Nginx with default version
   apt: name="nginx"  update_cache=yes  state=present force=yes
   when: nginx_version is not defined
